apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: admin-demo
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx-example
  rules:
  - http:
      paths:
      - path: /admin
        pathType: Prefix
        backend:
          service:
            name: admin-demo
            port:
              number: 8000
